[2025-03-11T20:07:22.455+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T20:07:22.463+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_load_to_s3 manual__2025-03-11T19:54:17.901673+00:00 [queued]>
[2025-03-11T20:07:22.469+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_load_to_s3 manual__2025-03-11T19:54:17.901673+00:00 [queued]>
[2025-03-11T20:07:22.469+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-03-11T20:07:22.484+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): tsk_load_to_s3> on 2025-03-11 19:54:17.901673+00:00
[2025-03-11T20:07:22.489+0000] {standard_task_runner.py:72} INFO - Started process 6325 to run task
[2025-03-11T20:07:22.491+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'redfin_analytics_dag', 'tsk_load_to_s3', 'manual__2025-03-11T19:54:17.901673+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/redfin_analytics.py', '--cfg-path', '/tmp/tmpaz_qnxb1']
[2025-03-11T20:07:22.492+0000] {standard_task_runner.py:105} INFO - Job 102: Subtask tsk_load_to_s3
[2025-03-11T20:07:22.532+0000] {task_command.py:467} INFO - Running <TaskInstance: redfin_analytics_dag.tsk_load_to_s3 manual__2025-03-11T19:54:17.901673+00:00 [running]> on host ip-172-31-7-71.eu-west-2.compute.internal
[2025-03-11T20:07:22.588+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dengineer420@gmail.com' AIRFLOW_CTX_DAG_OWNER='Rahul' AIRFLOW_CTX_DAG_ID='redfin_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T19:54:17.901673+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T19:54:17.901673+00:00'
[2025-03-11T20:07:22.588+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T20:07:22.589+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T20:07:22.589+0000] {logging_mixin.py:190} INFO - Current task name:tsk_load_to_s3 state:running start_date:2025-03-11 20:07:22.464045+00:00
[2025-03-11T20:07:22.589+0000] {logging_mixin.py:190} INFO - Dag name:redfin_analytics_dag and current dag run status:running
[2025-03-11T20:07:22.589+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T20:07:22.590+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-11T20:07:22.590+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv s3://redfin-raw-data-yt/data/redfin_data_chunk_0.csv} s3://redfin-raw-data-yt']
[2025-03-11T20:07:22.599+0000] {subprocess.py:99} INFO - Output:
[2025-03-11T20:07:23.159+0000] {subprocess.py:106} INFO - fatal error: An error occurred (404) when calling the HeadObject operation: Key "data/redfin_data_chunk_0.csv}" does not exist
[2025-03-11T20:07:23.243+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-11T20:07:23.251+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-11T20:07:23.256+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-11T20:07:23.257+0000] {logging_mixin.py:190} INFO - Task start:2025-03-11 20:07:22.464045+00:00 end:2025-03-11 20:07:23.256441+00:00 duration:0.792396
[2025-03-11T20:07:23.257+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): tsk_load_to_s3> dag:<DAG: redfin_analytics_dag> dagrun:<DagRun redfin_analytics_dag @ 2025-03-11 19:54:17.901673+00:00: manual__2025-03-11T19:54:17.901673+00:00, state:running, queued_at: 2025-03-11 19:54:17.914446+00:00. externally triggered: True>
[2025-03-11T20:07:23.257+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-03-11T20:07:23.257+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=redfin_analytics_dag, task_id=tsk_load_to_s3, run_id=manual__2025-03-11T19:54:17.901673+00:00, execution_date=20250311T195417, start_date=20250311T200722, end_date=20250311T200723
[2025-03-11T20:07:23.287+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T20:07:23.288+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 102 for task tsk_load_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 6325)
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-11T20:07:23.306+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-11T20:07:23.326+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T20:07:23.327+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
