[2025-03-06T00:58:13.236+0000] {processor.py:186} INFO - Started process (PID=3314) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T00:58:13.237+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T00:58:13.240+0000] {logging_mixin.py:190} INFO - [2025-03-06T00:58:13.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T00:58:13.251+0000] {logging_mixin.py:190} INFO - [2025-03-06T00:58:13.246+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 6, in <module>
    from functions import extract_data, transform_data
  File "/home/ubuntu/airflow/dags/functions.py", line 1, in <module>
    from datetime import deltatime, datetime
ImportError: cannot import name 'deltatime' from 'datetime' (/usr/lib/python3.12/datetime.py). Did you mean: 'datetime'?
[2025-03-06T00:58:13.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T00:58:13.281+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.053 seconds
[2025-03-06T00:59:12.936+0000] {processor.py:186} INFO - Started process (PID=3909) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T00:59:12.938+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T00:59:12.940+0000] {logging_mixin.py:190} INFO - [2025-03-06T00:59:12.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T00:59:12.945+0000] {logging_mixin.py:190} INFO - [2025-03-06T00:59:12.943+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 6, in <module>
    from functions import extract_data, transform_data
  File "/home/ubuntu/airflow/dags/functions.py", line 1, in <module>
    from datetime import deltatime, datetime
ImportError: cannot import name 'deltatime' from 'datetime' (/usr/lib/python3.12/datetime.py). Did you mean: 'datetime'?
[2025-03-06T00:59:12.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T00:59:12.967+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.037 seconds
[2025-03-06T01:00:09.733+0000] {processor.py:186} INFO - Started process (PID=4210) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:00:09.735+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:00:09.737+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:00:09.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:00:09.743+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:00:09.741+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 6, in <module>
    from functions import extract_data, transform_data
  File "/home/ubuntu/airflow/dags/functions.py", line 1, in <module>
    from datetime import deltatime, datetime
ImportError: cannot import name 'deltatime' from 'datetime' (/usr/lib/python3.12/datetime.py). Did you mean: 'datetime'?
[2025-03-06T01:00:09.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:00:09.770+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.043 seconds
[2025-03-06T01:01:11.142+0000] {processor.py:186} INFO - Started process (PID=4809) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:01:11.144+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:01:11.146+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:01:11.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:01:11.259+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:01:11.259+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:01:11.378+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:01:11.376+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 10, in <module>
    s3_client = boto3.clinet('s3')
                ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'clinet'. Did you mean: 'client'?
[2025-03-06T01:01:11.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:01:11.401+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.265 seconds
[2025-03-06T01:01:43.608+0000] {processor.py:186} INFO - Started process (PID=4902) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:01:43.609+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:01:43.612+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:01:43.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:01:43.694+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:01:43.693+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:01:43.792+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:01:43.790+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 10, in <module>
    s3_client = boto3.clinet('s3')
                ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'clinet'. Did you mean: 'client'?
[2025-03-06T01:01:43.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:01:43.834+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.234 seconds
[2025-03-06T01:02:14.386+0000] {processor.py:186} INFO - Started process (PID=5113) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:02:14.388+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:02:14.390+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:02:14.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:02:14.467+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:02:14.467+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:02:14.563+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:02:14.561+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 10, in <module>
    s3_client = boto3.clinet('s3')
                ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'clinet'. Did you mean: 'client'?
[2025-03-06T01:02:14.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:02:14.585+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.205 seconds
[2025-03-06T01:03:13.430+0000] {processor.py:186} INFO - Started process (PID=5293) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:03:13.432+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:03:13.434+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:03:13.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:03:13.515+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:03:13.515+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:03:13.630+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:03:13.628+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 10, in <module>
    s3_client = boto3.clinet('s3')
                ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'clinet'. Did you mean: 'client'?
[2025-03-06T01:03:13.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:03:13.654+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.232 seconds
[2025-03-06T01:04:13.187+0000] {processor.py:186} INFO - Started process (PID=5410) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:04:13.189+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:04:13.192+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:04:13.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:04:13.301+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:04:13.301+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:04:13.433+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:04:13.430+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 10, in <module>
    s3_client = boto3.clinet('s3')
                ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'clinet'. Did you mean: 'client'?
[2025-03-06T01:04:13.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:04:13.477+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.298 seconds
[2025-03-06T01:04:45.495+0000] {processor.py:186} INFO - Started process (PID=5501) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:04:45.497+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:04:45.499+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:04:45.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:04:45.589+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:04:45.588+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:04:45.688+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:04:45.686+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 10, in <module>
    s3_client = boto3.clinet('s3')
                ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'clinet'. Did you mean: 'client'?
[2025-03-06T01:04:45.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:04:45.715+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.226 seconds
[2025-03-06T01:05:17.670+0000] {processor.py:186} INFO - Started process (PID=5594) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:05:17.674+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:05:17.682+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:05:17.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:05:17.841+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:05:17.841+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:05:18.010+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:05:18.007+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 10, in <module>
    s3_client = boto3.clinet('s3')
                ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'clinet'. Did you mean: 'client'?
[2025-03-06T01:05:18.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:05:18.037+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.374 seconds
[2025-03-06T01:05:50.385+0000] {processor.py:186} INFO - Started process (PID=5626) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:05:50.386+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:05:50.389+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:05:50.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:05:50.467+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:05:50.466+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:05:50.551+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:05:50.550+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 10, in <module>
    s3_client = boto3.clinet('s3')
                ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'clinet'. Did you mean: 'client'?
[2025-03-06T01:05:50.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:05:50.584+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.206 seconds
[2025-03-06T01:06:21.397+0000] {processor.py:186} INFO - Started process (PID=5775) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:06:21.398+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:06:21.400+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:06:21.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:06:21.478+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:06:21.478+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:06:21.578+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:06:21.576+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 24, in <module>
    'retry_delay': timedelta(second=15)
                   ^^^^^^^^^^^^^^^^^^^^
TypeError: 'second' is an invalid keyword argument for __new__()
[2025-03-06T01:06:21.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:06:21.599+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.209 seconds
[2025-03-06T01:06:53.114+0000] {processor.py:186} INFO - Started process (PID=5927) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:06:53.116+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:06:53.119+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:06:53.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:06:53.233+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:06:53.232+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:06:53.338+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:06:53.337+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 24, in <module>
    'retry_delay': timedelta(second=15)
                   ^^^^^^^^^^^^^^^^^^^^
TypeError: 'second' is an invalid keyword argument for __new__()
[2025-03-06T01:06:53.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:06:53.362+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.254 seconds
[2025-03-06T01:07:24.410+0000] {processor.py:186} INFO - Started process (PID=6198) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:07:24.414+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:07:24.417+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:24.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:07:24.512+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:24.512+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:07:24.815+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:24.813+0000] {dagbag.py:387} ERROR - Failed to import: /home/ubuntu/airflow/dags/redfin_analytics.py
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/redfin_analytics.py", line 24, in <module>
    'retry_delay': timedelta(second=15)
                   ^^^^^^^^^^^^^^^^^^^^
TypeError: 'second' is an invalid keyword argument for __new__()
[2025-03-06T01:07:24.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:07:24.838+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.436 seconds
[2025-03-06T01:07:54.026+0000] {processor.py:186} INFO - Started process (PID=6346) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:07:54.027+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:07:54.031+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:07:54.109+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.109+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:07:54.390+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:07:54.484+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.484+0000] {override.py:1930} INFO - Created Permission View: can read on DAG:redfin_analytics_dag
[2025-03-06T01:07:54.498+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.497+0000] {override.py:1930} INFO - Created Permission View: can delete on DAG:redfin_analytics_dag
[2025-03-06T01:07:54.510+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.509+0000] {override.py:1930} INFO - Created Permission View: can edit on DAG:redfin_analytics_dag
[2025-03-06T01:07:54.526+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.525+0000] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:redfin_analytics_dag
[2025-03-06T01:07:54.536+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.535+0000] {override.py:1930} INFO - Created Permission View: can read on DAG Run:redfin_analytics_dag
[2025-03-06T01:07:54.546+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.546+0000] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:redfin_analytics_dag
[2025-03-06T01:07:54.558+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.558+0000] {override.py:1930} INFO - Created Permission View: can create on DAG Run:redfin_analytics_dag
[2025-03-06T01:07:54.559+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.559+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:07:54.573+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.573+0000] {dag.py:3262} INFO - Creating ORM DAG for redfin_analytics_dag
[2025-03-06T01:07:54.583+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:07:54.583+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:07:54.618+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.599 seconds
[2025-03-06T01:08:25.073+0000] {processor.py:186} INFO - Started process (PID=6496) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:08:25.074+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:08:25.076+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:08:25.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:08:25.171+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:08:25.171+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:08:25.543+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:08:25.559+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:08:25.559+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:08:25.581+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:08:25.580+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:08:25.616+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.551 seconds
[2025-03-06T01:08:54.419+0000] {processor.py:186} INFO - Started process (PID=6585) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:08:54.420+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:08:54.422+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:08:54.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:08:54.558+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:08:54.557+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:08:54.865+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:08:54.877+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:08:54.877+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:08:54.894+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:08:54.894+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:08:54.919+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.506 seconds
[2025-03-06T01:09:26.709+0000] {processor.py:186} INFO - Started process (PID=6795) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:09:26.710+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:09:26.713+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:09:26.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:09:26.798+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:09:26.798+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:09:27.127+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:09:27.145+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:09:27.145+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:09:27.174+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:09:27.174+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:09:27.200+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.498 seconds
[2025-03-06T01:09:58.829+0000] {processor.py:186} INFO - Started process (PID=6825) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:09:58.830+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:09:58.833+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:09:58.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:09:58.933+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:09:58.933+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:09:59.246+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:09:59.265+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:09:59.265+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:09:59.284+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:09:59.284+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:09:59.311+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.492 seconds
[2025-03-06T01:10:29.471+0000] {processor.py:186} INFO - Started process (PID=6919) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:10:29.473+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:10:29.475+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:10:29.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:10:29.573+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:10:29.573+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:10:29.899+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:10:29.913+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:10:29.912+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:10:29.932+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:10:29.932+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:10:29.955+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.491 seconds
[2025-03-06T01:11:00.152+0000] {processor.py:186} INFO - Started process (PID=6948) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:11:00.153+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:11:00.155+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:11:00.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:11:00.299+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:11:00.298+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:11:00.625+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:11:00.642+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:11:00.641+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:11:00.669+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:11:00.669+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:11:00.693+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.550 seconds
[2025-03-06T01:11:30.811+0000] {processor.py:186} INFO - Started process (PID=7038) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:11:30.812+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:11:30.814+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:11:30.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:11:30.908+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:11:30.908+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:11:31.259+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:11:31.273+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:11:31.273+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:11:31.292+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:11:31.292+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:11:31.318+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.514 seconds
[2025-03-06T01:12:03.081+0000] {processor.py:186} INFO - Started process (PID=7067) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:12:03.083+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:12:03.085+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:12:03.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:12:03.174+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:12:03.174+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:12:03.530+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:12:03.542+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:12:03.542+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:12:03.562+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:12:03.562+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:12:03.592+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.518 seconds
[2025-03-06T01:12:36.982+0000] {processor.py:186} INFO - Started process (PID=7159) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:12:36.986+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:12:36.989+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:12:36.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:12:37.084+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:12:37.083+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:12:37.510+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:12:37.540+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:12:37.539+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:12:37.582+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:12:37.581+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:12:37.610+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.635 seconds
[2025-03-06T01:13:08.740+0000] {processor.py:186} INFO - Started process (PID=7189) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:13:08.741+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:13:08.744+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:13:08.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:13:08.851+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:13:08.851+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:13:09.223+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:13:09.237+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:13:09.237+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:13:09.256+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:13:09.256+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:13:09.278+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.546 seconds
[2025-03-06T01:14:09.922+0000] {processor.py:186} INFO - Started process (PID=7369) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:14:09.923+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:14:09.926+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:14:09.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:14:10.016+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:14:10.016+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:14:10.342+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:14:10.356+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:14:10.355+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:14:10.380+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:14:10.379+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:14:10.410+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.496 seconds
[2025-03-06T01:14:40.639+0000] {processor.py:186} INFO - Started process (PID=7460) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:14:40.640+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:14:40.643+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:14:40.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:14:40.726+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:14:40.725+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:14:41.023+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:14:41.036+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:14:41.035+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:14:41.055+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:14:41.055+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:14:41.076+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.445 seconds
[2025-03-06T01:15:41.763+0000] {processor.py:186} INFO - Started process (PID=7762) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:15:41.769+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:15:41.772+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:15:41.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:15:41.896+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:15:41.895+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:15:42.276+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:15:42.294+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:15:42.293+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:15:42.315+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:15:42.315+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:15:42.347+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.603 seconds
[2025-03-06T01:16:13.860+0000] {processor.py:186} INFO - Started process (PID=7792) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:16:13.862+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:16:13.865+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:16:13.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:16:13.948+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:16:13.948+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:16:14.229+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:16:14.241+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:16:14.241+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:16:14.257+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:16:14.257+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:16:14.280+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.427 seconds
[2025-03-06T01:17:13.431+0000] {processor.py:186} INFO - Started process (PID=7913) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:17:13.433+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:17:13.437+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:17:13.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:17:13.529+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:17:13.528+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:17:13.925+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:17:13.943+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:17:13.942+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:17:13.965+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:17:13.965+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:17:14.001+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.579 seconds
[2025-03-06T01:17:45.024+0000] {processor.py:186} INFO - Started process (PID=8224) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:17:45.026+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:17:45.028+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:17:45.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:17:45.114+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:17:45.113+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:17:45.466+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:17:45.479+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:17:45.478+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:17:45.498+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:17:45.498+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:17:45.521+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.503 seconds
[2025-03-06T01:18:44.935+0000] {processor.py:186} INFO - Started process (PID=8463) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:18:44.937+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:18:44.940+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:18:44.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:18:45.137+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:18:45.136+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:18:45.524+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:18:45.539+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:18:45.539+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:18:45.561+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:18:45.560+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:18:45.588+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.660 seconds
[2025-03-06T01:19:18.159+0000] {processor.py:186} INFO - Started process (PID=8553) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:19:18.161+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:19:18.163+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:19:18.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:19:18.277+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:19:18.277+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:19:18.674+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:19:18.693+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:19:18.693+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:19:18.728+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:19:18.728+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:19:18.758+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.608 seconds
[2025-03-06T01:19:52.146+0000] {processor.py:186} INFO - Started process (PID=8584) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:19:52.147+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:19:52.149+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:19:52.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:19:52.226+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:19:52.226+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:19:52.508+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:19:52.520+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:19:52.520+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:19:52.538+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:19:52.537+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-05 00:00:00+00:00, run_after=2025-03-06 00:00:00+00:00
[2025-03-06T01:19:52.559+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 0.420 seconds
[2025-03-06T01:22:46.966+0000] {processor.py:186} INFO - Started process (PID=9618) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:22:46.968+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:22:46.969+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:22:46.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:22:47.156+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:22:47.156+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:22:47.923+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:22:47.932+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:22:47.932+0000] {taskinstance.py:3315} ERROR - {'DAG Id': 'redfin_analytics_dag', 'Task Id': 'tsk_extract_redfin_data', 'Run Id': 'scheduled__2025-03-05T00:00:00+00:00', 'Hostname': 'ip-172-31-7-71.eu-west-2.compute.internal'}
[2025-03-06T01:22:47.950+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-06T01:22:47.950+0000] {logging_mixin.py:190} INFO - Task start:2025-03-06 01:20:03.253593+00:00 end:2025-03-06 01:22:47.949468+00:00 duration:164.695875
[2025-03-06T01:22:47.950+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): tsk_extract_redfin_data> dag:<DAG: redfin_analytics_dag> dagrun:<DagRun redfin_analytics_dag @ 2025-03-05 00:00:00+00:00: scheduled__2025-03-05T00:00:00+00:00, state:running, queued_at: 2025-03-06 01:19:59.809170+00:00. externally triggered: False>
[2025-03-06T01:22:47.950+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'redfin_analytics_dag', 'Task Id': 'tsk_extract_redfin_data', 'Run Id': 'scheduled__2025-03-05T00:00:00+00:00', 'Hostname': 'ip-172-31-7-71.eu-west-2.compute.internal'}
[2025-03-06T01:22:47.951+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:22:47.951+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=redfin_analytics_dag, task_id=tsk_extract_redfin_data, run_id=scheduled__2025-03-05T00:00:00+00:00, execution_date=20250305T000000, start_date=20250306T012003, end_date=20250306T012247
[2025-03-06T01:22:47.989+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:22:47.989+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data scheduled__2025-03-05T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-03-06T01:22:48.012+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:22:48.012+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:22:48.030+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:22:48.030+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-06 00:00:00+00:00, run_after=2025-03-07 00:00:00+00:00
[2025-03-06T01:22:48.050+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 1.093 seconds
[2025-03-06T01:25:39.958+0000] {processor.py:186} INFO - Started process (PID=11336) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:25:39.960+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:25:39.961+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:25:39.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:25:40.171+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:25:40.170+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:25:40.916+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:25:40.944+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:25:40.943+0000] {taskinstance.py:3315} ERROR - {'DAG Id': 'redfin_analytics_dag', 'Task Id': 'tsk_extract_redfin_data', 'Run Id': 'manual__2025-03-06T01:19:59.613236+00:00', 'Hostname': 'ip-172-31-7-71.eu-west-2.compute.internal'}
[2025-03-06T01:25:40.982+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-06T01:25:40.982+0000] {logging_mixin.py:190} INFO - Task start:2025-03-06 01:22:53.429947+00:00 end:2025-03-06 01:25:40.981651+00:00 duration:167.551704
[2025-03-06T01:25:40.982+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): tsk_extract_redfin_data> dag:<DAG: redfin_analytics_dag> dagrun:<DagRun redfin_analytics_dag @ 2025-03-06 01:19:59.613236+00:00: manual__2025-03-06T01:19:59.613236+00:00, state:running, queued_at: 2025-03-06 01:19:59.660991+00:00. externally triggered: True>
[2025-03-06T01:25:40.983+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'redfin_analytics_dag', 'Task Id': 'tsk_extract_redfin_data', 'Run Id': 'manual__2025-03-06T01:19:59.613236+00:00', 'Hostname': 'ip-172-31-7-71.eu-west-2.compute.internal'}
[2025-03-06T01:25:40.983+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:25:40.983+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=redfin_analytics_dag, task_id=tsk_extract_redfin_data, run_id=manual__2025-03-06T01:19:59.613236+00:00, execution_date=20250306T011959, start_date=20250306T012253, end_date=20250306T012540
[2025-03-06T01:25:41.044+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:25:41.044+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2025-03-06T01:19:59.613236+00:00 [up_for_retry]> in state up_for_retry
[2025-03-06T01:25:41.081+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:25:41.081+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:25:41.118+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:25:41.117+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-06 00:00:00+00:00, run_after=2025-03-07 00:00:00+00:00
[2025-03-06T01:25:41.141+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 1.191 seconds
[2025-03-06T01:28:37.194+0000] {processor.py:186} INFO - Started process (PID=12723) to work on /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:28:37.196+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow/dags/redfin_analytics.py for tasks to queue
[2025-03-06T01:28:37.197+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:28:37.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:28:37.402+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:28:37.402+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-03-06T01:28:38.280+0000] {processor.py:925} INFO - DAG(s) 'redfin_analytics_dag' retrieved from /home/ubuntu/airflow/dags/redfin_analytics.py
[2025-03-06T01:28:38.296+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:28:38.296+0000] {taskinstance.py:3315} ERROR - {'DAG Id': 'redfin_analytics_dag', 'Task Id': 'tsk_extract_redfin_data', 'Run Id': 'scheduled__2025-03-05T00:00:00+00:00', 'Hostname': 'ip-172-31-7-71.eu-west-2.compute.internal'}
[2025-03-06T01:28:38.326+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-06T01:28:38.326+0000] {logging_mixin.py:190} INFO - Task start:2025-03-06 01:25:46.611155+00:00 end:2025-03-06 01:28:38.325599+00:00 duration:171.714444
[2025-03-06T01:28:38.326+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): tsk_extract_redfin_data> dag:<DAG: redfin_analytics_dag> dagrun:<DagRun redfin_analytics_dag @ 2025-03-05 00:00:00+00:00: scheduled__2025-03-05T00:00:00+00:00, state:running, queued_at: 2025-03-06 01:19:59.809170+00:00. externally triggered: False>
[2025-03-06T01:28:38.327+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'redfin_analytics_dag', 'Task Id': 'tsk_extract_redfin_data', 'Run Id': 'scheduled__2025-03-05T00:00:00+00:00', 'Hostname': 'ip-172-31-7-71.eu-west-2.compute.internal'}
[2025-03-06T01:28:38.328+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:28:38.327+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=redfin_analytics_dag, task_id=tsk_extract_redfin_data, run_id=scheduled__2025-03-05T00:00:00+00:00, execution_date=20250305T000000, start_date=20250306T012546, end_date=20250306T012838
[2025-03-06T01:28:38.377+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:28:38.376+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data scheduled__2025-03-05T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-03-06T01:28:38.414+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:28:38.413+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-06T01:28:38.431+0000] {logging_mixin.py:190} INFO - [2025-03-06T01:28:38.431+0000] {dag.py:4180} INFO - Setting next_dagrun for redfin_analytics_dag to 2025-03-06 00:00:00+00:00, run_after=2025-03-07 00:00:00+00:00
[2025-03-06T01:28:38.454+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow/dags/redfin_analytics.py took 1.267 seconds
